#include <stdio.h>
#include "hashtable.h"

#define PRINT_ARR(ar) 

static void print_user_data(char **data)
{
    if (!data)
        return;
    printf("%p\n", data);
    printf("%s \n", *data);
}

static void print_ht(hashtable_t *ht)
{
    ht_foreach(ht, print_user_data);
}

int main(void)
{
    hashtable_t *ht = ht_create(hash, 10);
    char *val1 = "swag";
    char *val2 = "test";
    char *val3 = "test2";

    ht_insert(ht, &HT_INTO_KEY("test"), &val1);
    ht_insert(ht, &HT_INTO_KEY("ghg"), &val1);
    ht_insert(ht, &HT_INTO_KEY("yo"), &val2);
    ht_insert(ht, &HT_INTO_KEY("yo"), &val3);
    ht_insert(ht, &HT_INTO_KEY("yo"), &val3);
    ht_insert(ht, &HT_INTO_KEY("yo"), &val3);
    ht_insert(ht, &HT_INTO_KEY("yo"), &val3);
    ht_insert(ht, &HT_INTO_KEY("yo"), &val3);
    ht_insert(ht, &HT_INTO_KEY("yo"), &val3);
    ht_insert(ht, &HT_INTO_KEY("yo"), &val3);
    ht_insert(ht, &HT_INTO_KEY("yo"), &val3);
    ht_insert(ht, &HT_INTO_KEY("yo"), &val3);
    ht_insert(ht, &HT_INTO_KEY("yo"), &val3);
    ht_insert(ht, &HT_INTO_KEY("yo"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae21"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae22"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae23"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae24"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae27"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae27"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae30"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae35"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae36"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae37"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae39"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae40"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae42"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae46"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae47"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae19"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae18"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae17"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae16"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae12"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae-2"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae-7"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae-14"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae-1"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae52"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae63"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae72"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae69"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae85"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae86"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae96"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae46"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2121"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2122"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2123"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2124"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2125"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2131"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2135"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2138"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2139"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2146"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2157"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2159"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2161"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2167"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2178"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2185"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2306"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2172"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2144"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2151"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2176"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2109"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2119"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2118"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae212"), &val2);
    ht_insert(ht, &HT_INTO_KEY("ae2104"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2095"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2077"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae211)"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2088"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2101"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2013"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2067"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2062"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2100"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2101"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2110"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2089"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2085"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae208"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2092"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2105"), &val3);
    ht_insert(ht, &HT_INTO_KEY("ae2109"), &val3);
    ht_insert(ht, &HT_INTO_KEY("e2120"), &val3);
    ht_insert(ht, &HT_INTO_KEY("a2120"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefm0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefl0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefo0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefi0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefy0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aeft0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefr0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefe0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefa0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefz0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefw0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefc0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefx0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefc"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefb0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aefa0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2z"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2s"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2a"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2p"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2o"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2n"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2m"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2l"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2k"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2j"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2i"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2h"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2f"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2e"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2g"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2d"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2c"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2b"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2a"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef74"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef101"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef82"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef79"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef82"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef80"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef58"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef84"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef87"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef66"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef84"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef78"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef75"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef96"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef82"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef71"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef15"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef16"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef34"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef17"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef19"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef93"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef68"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef59"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef66"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef68"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef69"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef63"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef52"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef48"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef48"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef45"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef42"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef40"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef38"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef37"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef34"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef33"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef31"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef21"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef24"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef28"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef27"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef21"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef14"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef13"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef7"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef0"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef5"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef5"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef4"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef2"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef1"), &val3);
    ht_insert(ht, &HT_INTO_KEY("aef0"), &val3);
    print_ht(ht);

    ht_destroy(ht);

}
